services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: IRLS
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    environment:
      - RUN_QUEUE=1
    depends_on:
      - app
