services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: IRLS
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=80

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3
    depends_on:
      - app